### ISSUE TITLE
用token进行ws连接会报错:token验证失败","echo":null

### ISSUE THREAD

**Issue by alexyutmp** [w1ndys/W1ndysBotFrame#78]
2024-12-31 21:33:15 INFO:root:日志文件名: logs/2024-12-31_21-33-15.log
2024-12-31 21:33:15 DEBUG:asyncio:Using selector: KqueueSelector
2024-12-31 21:33:15 INFO:root:正在连接到机器人...
2024-12-31 21:33:15 INFO:root:连接地址: ws://xxx.0.106.38:3001
2024-12-31 21:33:15 DEBUG:websockets.client:= connection is CONNECTING
2024-12-31 21:33:15 DEBUG:websockets.client:> GET / HTTP/1.1
2024-12-31 21:33:15 DEBUG:websockets.client:> Host: xxx.0.106.38:3001
2024-12-31 21:33:15 DEBUG:websockets.client:> Upgrade: websocket
2024-12-31 21:33:15 DEBUG:websockets.client:> Connection: Upgrade
2024-12-31 21:33:15 DEBUG:websockets.client:> Sec-WebSocket-Key: AcCkg/Ks3DRUR7+0ENapUQ==
2024-12-31 21:33:15 DEBUG:websockets.client:> Sec-WebSocket-Version: 13
2024-12-31 21:33:15 DEBUG:websockets.client:> Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
2024-12-31 21:33:15 DEBUG:websockets.client:> User-Agent: Python/3.9 websockets/14.1
2024-12-31 21:33:15 DEBUG:websockets.client:< HTTP/1.1 101 Switching Protocols
2024-12-31 21:33:15 DEBUG:websockets.client:< Upgrade: websocket
2024-12-31 21:33:15 DEBUG:websockets.client:< Connection: Upgrade
2024-12-31 21:33:15 DEBUG:websockets.client:< Sec-WebSocket-Accept: oE8t0xQwJC6BJ8116NhS0jcophc=
2024-12-31 21:33:15 DEBUG:websockets.client:= connection is OPEN
2024-12-31 21:33:15 DEBUG:websockets.client:< TEXT '{"status":"failed","retcode":1403,"data":null,"...token验证失败","echo":null}' [118 bytes]
2024-12-31 21:33:15 DEBUG:websockets.client:< CLOSE 1005 (no status received [internal]) [0 bytes]
2024-12-31 21:33:15 DEBUG:websockets.client:> CLOSE 1005 (no status received [internal]) [0 bytes]
2024-12-31 21:33:15 DEBUG:websockets.client:= connection is CLOSING
2024-12-31 21:33:15 INFO:root:已连接到机器人。当前时间: 2024-12-31 21:33:15
2024-12-31 21:33:15 DEBUG:websockets.client:< EOF
2024-12-31 21:33:15 DEBUG:websockets.client:> EOF
2024-12-31 21:33:15 DEBUG:websockets.client:= connection is CLOSED
2024-12-31 21:33:15 DEBUG:websockets.client:x half-closing TCP connection
2024-12-31 21:33:15 ERROR:root:连接失败，正在重试: received 1005 (no status received [internal]); then sent 1005 (no status received [internal]) 当前时间: 2024-12-31 21:33:15
2024-12-31 21:33:16 INFO:root:正在连接到机器人...
2024-12-31 21:33:16 INFO:root:连接地址: ws://xxx.0.106.38:3001
2024-12-31 21:33:16 DEBUG:websockets.client:= connection is CONNECTING
2024-12-31 21:33:16 DEBUG:websockets.client:> GET / HTTP/1.1
2024-12-31 21:33:16 DEBUG:websockets.client:> Host: xxx.0.106.38:3001
2024-12-31 21:33:16 DEBUG:websockets.client:> Upgrade: websocket
2024-12-31 21:33:16 DEBUG:websockets.client:> Connection: Upgrade
2024-12-31 21:33:16 DEBUG:websockets.client:> Sec-WebSocket-Key: yewYBp0aR39ZxbcxJDnfeA==
2024-12-31 21:33:16 DEBUG:websockets.client:> Sec-WebSocket-Version: 13
2024-12-31 21:33:16 DEBUG:websockets.client:> Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
2024-12-31 21:33:16 DEBUG:websockets.client:> User-Agent: Python/3.9 websockets/14.1
2024-12-31 21:33:16 DEBUG:websockets.client:< HTTP/1.1 101 Switching Protocols
2024-12-31 21:33:16 DEBUG:websockets.client:< Upgrade: websocket
2024-12-31 21:33:16 DEBUG:websockets.client:< Connection: Upgrade
2024-12-31 21:33:16 DEBUG:websockets.client:< Sec-WebSocket-Accept: Yme5mfDcSjvj3bgsnJL0Zm04kwQ=
2024-12-31 21:33:16 DEBUG:websockets.client:= connection is OPEN
2024-12-31 21:33:16 DEBUG:websockets.client:< TEXT '{"status":"failed","retcode":1403,"data":null,"...token验证失败","echo":null}' [118 bytes]
2024-12-31 21:33:16 DEBUG:websockets.client:< CLOSE 1005 (no status received [internal]) [0 bytes]
2024-12-31 21:33:16 DEBUG:websockets.client:> CLOSE 1005 (no status received [internal]) [0 bytes]
2024-12-31 21:33:16 DEBUG:websockets.client:= connection is CLOSING
2024-12-31 21:33:16 INFO:root:已连接到机器人。当前时间: 2024-12-31 21:33:16
2024-12-31 21:33:16 DEBUG:websockets.client:< EOF
2024-12-31 21:33:16 DEBUG:websockets.client:> EOF
2024-12-31 21:33:16 DEBUG:websockets.client:= connection is CLOSED
2024-12-31 21:33:16 DEBUG:websockets.client:x half-closing TCP connection
2024-12-31 21:33:16 ERROR:root:连接失败，正在重试: received 1005 (no status received [internal]); then sent 1005 (no status received [internal]) 当前时间: 2024-12-31 21:33:16
Traceback (most recent call last):
  File "/Users/alex/PycharmProjects/QQBot/W1ndysBot/app/main.py", line 32, in <module>
    asyncio.run(main())
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1854, in _run_once
    event_list = self._selector.select(timeout)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

**Comment by alexyutmp** [comment]
尝试在webui取消ws的token, 然后在bot中的config把token设为None,可以正常连接

**Comment by w1ndys** [comment]
问题已收到，正在定位
> 我平时都是在一台服务器运行的没用token，没试过这个，修复了我再看一下

**Comment by w1ndys** [comment]
已修复https://github.com/W1ndysBot/W1ndysBot/commit/ebbff81dad21c07a5961909a5ed0380795fdee1a

**Comment by w1ndys** [comment]
上个bug修复后出现了新bug，即无token的时候传入请求头会报错，现已修复https://github.com/W1ndysBot/W1ndysBot/commit/e9e910b307dd3acfcc3cde8ef670ab2eca6f3a26
